### ISSUE TITLE
feed-io can't update https://web.dev/feed.xml

### ISSUE THREAD

**Issue by mogoh** [alexdebril/feed-io#313] opened 2020-12-12 16:41 UTC
As the title says.

See also: https://github.com/nextcloud/news/discussions/976#discussioncomment-197047

**Comment by alexdebril** [comment] 2020-12-12 16:56
See my response in nextcloud's issue

**Comment by mogoh** [comment] 2020-12-12 17:07
Thanks.

**Comment by alexdebril** [comment] 2020-12-13 14:38
I'm closing this issue as the root cause is a bug in the feed itself. It can't be solved with a harmless workaround so I prefer to contact the publisher and them to fix it instead.

**Closed by alexdebril** 2020-12-13 14:38 UTC
Labels: wontfix
