### ISSUE TITLE
Impossible to convert date

### ISSUE THREAD

**Issue by Grotax** [alexdebril/feed-io#209] opened 2019-03-22 08:37 UTC
We got an error report, https://github.com/nextcloud/news/issues/461 for the following feed:
https://sourceforge.net/projects/cheeseburgerdumplings/rss?path=/15.1/dumpling

w3c-validator: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fcheeseburgerdumplings%2Frss%3Fpath%3D%2F15.1%2Fdumpling

As you may know, we are currently using 3.0 but I also tested 4.1. The full error:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Impossible to convert date : Fri, 22 Mar 2019 08:24:31 UT in /home/grotax/git/feed-io/src/FeedIo/Rule/DateTimeBuilder.php:150
Stack trace:
#0 /home/grotax/git/feed-io/src/FeedIo/Rule/DateTimeBuilder.php(136): FeedIo\Rule\DateTimeBuilder->stringToDateTime('Fri, 22 Mar 201...')
#1 /home/grotax/git/feed-io/src/FeedIo/Rule/ModifiedSince.php(26): FeedIo\Rule\DateTimeBuilder->convertToDateTime('Fri, 22 Mar 201...')
#2 /home/grotax/git/feed-io/src/FeedIo/Parser/XmlParser.php(114): FeedIo\Rule\ModifiedSince->setProperty(Object(FeedIo\Feed), Object(DOMElement))
#3 /home/grotax/git/feed-io/src/FeedIo/Parser/XmlParser.php(95): FeedIo\Parser\XmlParser->handleNode(Object(FeedIo\Feed), Object(DOMElement), Object(FeedIo\RuleSet))
#4 /home/grotax/git/feed-io/src/FeedIo/Parser/XmlParser.php(53): FeedIo\Parser\XmlParser->parseNode(Object(FeedIo\Feed), Object(DOMElement), Object(FeedIo\RuleSet))
#5 /home/grotax/git/feed-io/src/FeedIo/ParserAbstract.php(70): FeedIo\Parser\XmlParser->parseConten in /home/grotax/git/feed-io/src/FeedIo/Reader.php on line 122
```

**Comment by alexdebril** [comment] 2019-03-22 15:05
The 'C' is missing in the date's timezone, it's the root cause of the issue:

```shell
 php -a
Interactive mode enabled

php > $stringDate = 'Fri, 22 Mar 2019 14:54:24 UT';
php > $date = new \DateTime($stringDate);
PHP Warning:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (Fri, 22 Mar 2019 14:54:24 UT) at position 26 (U): The timezone could not be found in the database in php shell code:1
Stack trace:
#0 php shell code(1): DateTime->__construct('Fri, 22 Mar 201...')
#1 {main}
  thrown in php shell code on line 1
```

I'm opened to automatically fix malformed dates like this, although I don't see a short-term solution to that one. Do you know any PHP library to do this kind of thing ?

**Comment by Grotax** [comment] 2019-03-22 15:40
Not directly but we used picofeed which is now discontinued. Picofeed was able to parse the feed so I checked the DateParser: https://github.com/aaronpk/picofeed/blob/f79898e4e2508bbebcfb21488a7f20e67ea49090/lib/PicoFeed/Parser/DateParser.php

But I'm not sure if I like this approach :)

**Comment by alexdebril** [comment] 2019-03-26 13:59
In a very old version of rss-atom-bundle I had a `guessDateFormat` method to solve this kind of problem. I should have tagged each issues related to wrong date formats so I could count them... I finally decided to create a new instance of `DateTime` and let it deal with the date format, which works in most cases. But I never figured out a letter could be missing from the timezone, it looks so absurd to me...

Anyway, I don't think we could fix this without trying to guess the date format if the `DateTime`'s contructor is unable to do it. So Picofeed's approach is the one :)

**Comment by alexdebril** [comment] 2019-04-01 08:34
Sorry I didn't remembered well how the Date is built. I though I did dropped the date guessing strategy but it's actually still implemented this way.

Look at https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Rule/DateTimeBuilder.php

So, you just need to add extra date formats to feed-io and you're good to go : 

```php
<?php

require 'vendor/autoload.php';

$feedIo = \FeedIo\Factory::create()->getFeedIo();

$feedIo->addDateFormats(
    [
        'D, d M Y H:i:s \U\T',
    ]
);

$result = $feedIo->read('https://sourceforge.net/projects/cheeseburgerdumplings/rss?path=/15.1/dumpling');

echo "feed title : {$result->getFeed()->getTitle()} \n ";

foreach ($result->getFeed() as $item) {
    echo "item title : {$item->getTitle()} \n ";
}
```

**Comment by Grotax** [comment] 2019-04-01 08:55
Yes I noticed that. @SMillerDev what's your opinion on that?

**Comment by SMillerDev** [comment] 2019-04-01 10:03
I don't have any opinions on this. If you want to make a PR I'm fine with it.

**Comment by kratz00** [comment] 2019-04-12 08:27
> The 'C' is missing in the date's timezone, it's the root cause of the issue:

According to RFC 822 (http://www.faqs.org/rfcs/rfc822.html)

> Time zone may be indicated in several ways.  "UT" is Universal  Time  (formerly called "Greenwich Mean Time");

So *UTC* would not be valid for a *pubDate* element.

**Comment by alexdebril** [comment] 2019-04-12 08:56
I don't think UTC wouldn't be valid for a pubDate element as it's a valid time zone. We could have an infinite debate on why PHP doesn't support UT while it handles UTC and how confused everyone is about all time zones. 

Anyway, let's add this date format in the supported list and close this issue.

**Comment by kratz00** [comment] 2019-04-12 11:10
> I don't think UTC wouldn't be valid for a pubDate element as it's a valid time zone.

The *pubDate* element must be an RFC 822 date-time
Therefor *UTC* is not a valid time zone according to RFC 822, see https://tools.ietf.org/html/rfc822#section-5.1

I agree, PHP does not behave correctly. Both cases throw errors:

```
print_r(date_parse_from_format(DateTime::RSS, "Fri, 22 Mar 2019 14:54:24 UT"));
print_r(date_parse_from_format(DateTime::RFC822, "Fri, 22 Mar 2019 14:54:24 UT"));
```

**Closed** 2019-04-12 12:00 UTC
Labels: enhancement

**Comment by SMillerDev** [comment] 2019-04-12 12:33
You're the best @alexdebril
