### ISSUE TITLE
[request] Support for consuming RSS image child tags

### ISSUE THREAD

**Issue by lhartac** [alexdebril/feed-io#253] opened 2019-12-06 21:44 UTC
- Add RSS image child tag support for FeedInterface

In #230  support was added to get logo URLs via getLogo() which returns the image URL string. It'd also be helpful to consume the other image child tags available (description, width, height, link, title).

**Comment by alexdebril** [comment] 2020-02-05 12:51
Duplicate of #240

**Closed by alexdebril** 2020-02-05 12:51 UTC
