### ISSUE TITLE
Duplicate tags

### ISSUE THREAD

**Issue by Mopster** [alexdebril/feed-io#28] opened 2016-07-12 02:25 UTC
When adding a new element to an item, that elements gets repeated by the amount of preceding items in the feed.

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>Test</title>
    <link/>
    <guid>Test</guid>
    <description>public job list</description>
    <pubDate>Tue, 12 Jul 2016 11:17:28 +0900</pubDate>
    <lastPubDate>Tue, 12 Jul 2016 11:17:28 +0900</lastPubDate>
    <item>
      <title>esto es un trabajo</title>
      <category domain="">it</category>
      <link>http://mydomain.com</link>
      <guid>29</guid>
      <description>test</description>
      <pubDate>Tue, 12 Jul 2016 10:58:45 +0900</pubDate>
      <job_type>full time</job_type>
      <location>tokyo</location>
      <language>ja</language>
    </item>
    <item>
      <title>エンジニア</title>
      <category domain="">recruitment</category>
      <link>http://mydomain.com</link>
      <guid>28</guid>
      <description>test</description>
      <pubDate>Tue, 12 Jul 2016 11:01:31 +0900</pubDate>
      <job_type>full time</job_type>
      <location>Massachusetts</location>
      <language>ja</language>
      <job_type>full time</job_type>
      <location>Massachusetts</location>
      <language>ja</language>
      <expires>2016-07-14 00:00:00</expires>
    </item>
    <item>
      <title>Test job</title>
      <category domain=""/>
      <link>http://mydomain.com</link>
      <guid>23</guid>
      <description>test</description>
      <pubDate>Fri, 25 Sep 2015 15:41:55 +0900</pubDate>
      <job_type/>
      <location/>
      <language>en</language>
      <job_type/>
      <location/>
      <language>en</language>
      <expires/>
      <job_type/>
      <language>en</language>
    </item>
    <item>
      <title>宝石営業がタイトルなんですけどね。</title>
      <category domain=""/>
      <link>http://mydomain.com</link>
      <guid>17</guid>
      <description>test</description>
      <pubDate>Fri, 16 Oct 2015 14:59:29 +0900</pubDate>
      <job_type>full time</job_type>
      <location>東京都</location>
      <language/>
      <job_type>full time</job_type>
      <location>東京都</location>
      <language/>
      <expires/>
      <job_type>full time</job_type>
      <language/>
      <job_type>full time</job_type>
      <location>東京都</location>
      <language/>
    </item>
    <item>
      <title>清掃員</title>
      <category domain=""/>
      <link>http://mydomain.com</link>
      <guid>14</guid>
      <description>test</description>
      <pubDate>Wed, 18 Dec 2013 09:59:04 +0900</pubDate>
      <job_type>part time</job_type>
      <location/>
      <language/>
      <job_type>part time</job_type>
      <location/>
      <language/>
      <expires/>
      <job_type>part time</job_type>
      <language/>
      <job_type>part time</job_type>
      <location/>
      <language/>
      <job_type>part time</job_type>
      <location/>
      <language/>
    </item>
    <item>
      <title>リサーチャー / 内勤営業</title>
      <category domain=""/>
      <link>http://mydomain.com</link>
      <guid>13</guid>
      <description>test</description>
      <pubDate>Fri, 25 Sep 2015 15:43:51 +0900</pubDate>
      <job_type>contract to hire</job_type>
      <location>東京都</location>
      <language>ja</language>
      <job_type>contract to hire</job_type>
      <location>東京都</location>
      <language>ja</language>
      <expires/>
      <job_type>contract to hire</job_type>
      <language>ja</language>
      <job_type>contract to hire</job_type>
      <location>東京都</location>
      <language>ja</language>
      <job_type>contract to hire</job_type>
      <location>東京都</location>
      <language>ja</language>
      <job_type>contract to hire</job_type>
      <location>東京都</location>
      <language>ja</language>
    </item>
    <item>
      <title>Account Executive</title>
      <category domain=""/>
      <link>http://mydomain.com</link>
      <guid>11</guid>
      <description>test</description>
      <pubDate>Thu, 17 Sep 2015 22:17:41 +0900</pubDate>
      <job_type>full time</job_type>
      <location>東京</location>
      <language/>
      <job_type>full time</job_type>
      <location>東京</location>
      <language/>
      <expires/>
      <job_type>full time</job_type>
      <language/>
      <job_type>full time</job_type>
      <location>東京</location>
      <language/>
      <job_type>full time</job_type>
      <location>東京</location>
      <language/>
      <job_type>full time</job_type>
      <location>東京</location>
      <language/>
      <job_type>full time</job_type>
      <location>東京</location>
      <language/>
    </item>
  </channel>
</rss>
```

**Comment by alexdebril** [comment] 2016-08-01 11:41
Hi,

Can you show me the code please ? I'm trying to reproduce the issue

**Comment by Mopster** [comment] 2016-08-02 02:38
```

**Comment by alexdebril** [comment] 2016-08-02 07:55
I reproduce the issue with the following code : 

```php
<?php
require __DIR__.DIRECTORY_SEPARATOR.'bootstrap.php';

$feedIo = \FeedIo\Factory::create()->getFeedIo();

$feed = new \FeedIo\Feed();
$feed->setTitle("Tamago-DB Jobs");
$feed->setLastModified(new \DateTime());

$data = [
    [
        'title' => 'test 1',
        'job_type' => 'job type',
    ],
    [
        'title' => 'test 2',
    ]
];

foreach( $data as $row ) {
    $item = $feed->newItem();
    $item->setLastModified(new \DateTime());

    if ( array_key_exists('job_type', $row) ) {
        $item->set('job_type', $row['job_type']);
    }

    $feed->add($item);
}

$dom = $feedIo->toRss($feed);
$dom->formatOutput = true;
echo $dom->saveXML();

```

it outputs 

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>Tamago-DB Jobs</title>
    <link/>
    <guid/>
    <description/>
    <pubDate>Tue, 02 Aug 2016 07:52:30 +0000</pubDate>
    <lastPubDate>Tue, 02 Aug 2016 07:52:30 +0000</lastPubDate>
    <item>
      <title/>
      <link/>
      <guid/>
      <description/>
      <pubDate>Tue, 02 Aug 2016 07:52:30 +0000</pubDate>
      <job_type>job type</job_type>
    </item>
    <item>
      <title/>
      <link/>
      <guid/>
      <description/>
      <pubDate>Tue, 02 Aug 2016 07:52:30 +0000</pubDate>
      <job_type/>
    </item>
  </channel>
</rss>
```

The problem is : the node "job_type" should not exist in the second item. In your case it becomes worse because you have several nodes defined with Item::set() method which leads to several empty nodes.

**Comment by alexdebril** [comment] 2016-08-03 12:19
Bug fixed in https://github.com/alexdebril/feed-io/releases/tag/v2.2.2

**Closed by alexdebril** 2016-08-03 12:19 UTC
Labels: bug
