### ISSUE TITLE
Incorrect/useless value of the element for "author"

### ISSUE THREAD

**Issue by mvar** [alexdebril/feed-io#72] opened 2017-03-18 22:24 UTC
Hi, I'm parsing few feeds of some blogs and have encountered problem while trying to get name of the author of the post.

Example snippet from a feed of a blog (hosted by blogspot.com):

```xml
<feed>
    <!-- ... -->
    <entry>
        <author>
            <name>John Doe</name>
            <uri>http://www.blogger.com/profile/xxx</uri>
            <email>noreply@blogger.com</email>
            <gd:image rel='http://schemas.google.com/g/2005#thumbnail' width='16' height='16'
                      src='http://img1.blogblog.com/img/b16-rounded.gif'/>
        </author>
    </entry>
</feed>
```

In this case element value returned by `Item` will be like this:

```
John Doehttp://www.blogger.com/profile/xxxnoreply@blogger.com
```

Not much to do with this data.

@alexdebril is there any other way to get the name of the author? Thanks.

**Comment by alexdebril** [comment] 2017-05-02 07:05
Hi,

In the first place, feed-io didn't support author tags because it's an optional one and many feeds are not including it. So I decided this tag will be supported if someone asks for it, not before. And now there you are ... :-)

This feature will be in the next milestone, stay tuned.

**Comment by mvar** [comment] 2017-05-02 07:07
Thanks for update.

**Comment by alexdebril** [comment] 2017-05-03 17:49
Hi,

This is done in the new release. You can re-open this issue if something goes wrong.

Alex

**Comment by mvar** [comment] 2017-05-04 05:47
Thanks. I will check this later.

**Comment by mvar** [comment] 2017-05-16 19:18
@alexdebril I can't get this working.

Sample feed URL: http://googleadsdeveloper.blogspot.com/feeds/posts/default

PHP:

```php
        $url = 'http://googleadsdeveloper.blogspot.com/feeds/posts/default';

        $feed = $feedIo->read($url, null, $modifiedSince)->getFeed();

        /** @var Item $item */
        foreach ($feed as $item ) {
            dump($item->getLink());
            dump($item->getAuthor());
            dump($item->getAuthor()->getName());
            foreach ($item->getElementIterator('author') as $key => $media) {
                dump($key, $media);
            }

            break;
        }
```

Output:

```
DefaultController.php on line 153:
"http://feedproxy.google.com/~r/GoogleAdsDeveloperBlog/~3/1Eh8JHcr7Q4/adwords-improvements-for-enhanced-cpc.html"

DefaultController.php on line 154:
Author {#888 ▼
  #name: null
  #uri: null
  #email: null
}

DefaultController.php on line 155:
null
```

Environment:

```
$ composer show | grep debril
debril/feed-io                       v2.4.11 PHP library built to consume ...
debril/rss-atom-bundle               v3.0.6  RSS and Atom support for Symfony
```

**Comment by alexdebril** [comment] 2017-05-16 19:50
I see where the problem is, I'll release a patch soon.

Thank you for this feedback.

**Closed** 2017-05-16 21:54 UTC
Labels: enhancement
